# https://taskfile.dev

version: '3'

tasks:
  dev:
    cmds:
      - pnpm dev
  db:generate:
    cmds:
      - pnpm drizzle-kit generate
  db:migrate:
    cmds:
      - pnpm drizzle-kit migrate
  db:push:
    cmds:
      - pnpm drizzle-kit push
